"""
Funnel geometry from the BioSimSpace ``Funnel`` collective variable.

Source of truth: BioSimSpace 2024.4.1 (https://github.com/openbiosim/biosimspace),
``BioSimSpace/Metadynamics/CollectiveVariable/_funnel.py``.

* CV parameters: read from the BSS ``Funnel`` object (:func:`funnel_parameters`).
* Funnel radius: :func:`funnel_extent` calls ``Funnel.getExtent()`` (lines
  602-635): ``width / (1 + exp(steepness * (proj - inflection))) + buffer``
  in nm - the same expression BSS writes to PLUMED as ``wall_center``.
* Wall points: :func:`funnel_wall_points` contains a verbatim copy of the
  ``viewFunnel()`` wall-generation loop (lines 1098-1149), because
  ``viewFunnel`` itself returns ``None`` outside a notebook and a viewer (not
  coordinates) inside one.

Attribution for the copied ``viewFunnel`` code
----------------------------------------------
The block between the ``BEGIN/END verbatim`` markers in
:func:`funnel_wall_points` is copied from BioSimSpace 2024.4.1,
``BioSimSpace/Metadynamics/CollectiveVariable/_funnel.py``, function
``viewFunnel`` (lines 1098-1149). That file carries this notice::

    BioSimSpace: Making biomolecular simulation a breeze!
    Copyright: 2017-2025
    Authors: Lester Hedges <lester.hedges@gmail.com>
    BioSimSpace is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

and ``viewFunnel`` states: "The following is adapted from funnel_maker.py by
Dominykas Lukauskis." This package is therefore distributed under
GPL-3.0-or-later (see ``LICENSE``).

Adaptations to the copied block (nothing else is changed):

1. ``basis_ints``: the two ``_np.random.randint(1, 10)`` draws can be
   replaced by fixed integers (``None`` keeps BSS's random draws).
2. Radius mode: ``radius="viewfunnel"`` keeps BSS's radius line;
   ``radius="cv"`` (default) takes the radius from ``Funnel.getExtent()``,
   the radius the CV and PLUMED use. BSS's line evaluates the sigmoid with
   Angstrom distances while steepness is per nm (10x sharper than the CV).
3. NumPy output: coordinates are appended as numpy arrays instead of
   ``_SireVector`` pseudo-atoms; the pseudo-atom/element code is omitted.

Inputs: ``com0``/``com1`` are the P0/P1 passed in (the package derives them
from system-level atom indices, see ``p0_p1.py``); viewFunnel computes them
itself from protein-local indices (lines 1062-1082).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .p0_p1 import require_biosimspace


@dataclass(frozen=True)
class FunnelParameters:
    """Parameters of a BSS ``Funnel`` CV, in BSS's internal unit (nm)."""

    width_nm: float
    buffer_nm: float
    steepness_per_nm: float
    inflection_nm: float
    lower_bound_nm: float | None
    lower_bound_force_constant: float | None
    upper_bound_nm: float | None
    upper_bound_force_constant: float | None


def funnel_parameters(cv) -> FunnelParameters:
    """Read the parameters of a BSS ``Funnel`` collective variable."""

    def _bound(b):
        if b is None:
            return None, None
        return b.getValue().nanometers().value(), float(b.getForceConstant())

    lo, lo_k = _bound(cv.getLowerBound())
    hi, hi_k = _bound(cv.getUpperBound())
    return FunnelParameters(
        width_nm=cv.getWidth().nanometers().value(),
        buffer_nm=cv.getBuffer().nanometers().value(),
        steepness_per_nm=float(cv.getSteepness()),
        inflection_nm=cv.getInflection().nanometers().value(),
        lower_bound_nm=lo,
        lower_bound_force_constant=lo_k,
        upper_bound_nm=hi,
        upper_bound_force_constant=hi_k,
    )


def funnel_extent(cv, projection_nm) -> np.ndarray:
    """Funnel radius (nm) at projection(s) along the axis (nm), via ``cv.getExtent()``."""
    require_biosimspace()
    from BioSimSpace.Types import Length

    proj = np.atleast_1d(np.asarray(projection_nm, dtype=float))
    return np.array([cv.getExtent(Length(float(p), "nanometer")).nanometers().value() for p in proj])


def funnel_wall_points(
    p0: np.ndarray,
    p1: np.ndarray,
    cv,
    radius: str = "cv",
    basis_ints: tuple[int, int] | None = None,
) -> np.ndarray:
    """Funnel wall points (A), generated by the verbatim viewFunnel loop.

    Parameters
    ----------
    p0, p1 : (3,) arrays
        Funnel origin and inflection-side points (A) (viewFunnel's com0/com1).
    cv : BioSimSpace Funnel
    radius : {"cv", "viewfunnel"}
        ``"cv"`` (default): ``cv.getExtent()``, the CV/PLUMED radius.
        ``"viewfunnel"``: viewFunnel's own radius line (visualization reference).
    basis_ints : (a0, a1), optional
        Perpendicular-basis integers. ``None`` draws them exactly like
        viewFunnel: ``np.random.randint(1, 10)`` twice, numpy global RNG.

    Returns
    -------
    (n_rings * 8, 3) array in viewFunnel's order. As in BSS, an axis with a
    zero z-component divides by zero (numpy ``inf``/``nan`` + RuntimeWarning).
    """
    if radius not in ("cv", "viewfunnel"):
        raise ValueError("radius must be 'cv' or 'viewfunnel'.")
    radius_mode = radius
    require_biosimspace()
    from BioSimSpace.Types import Length

    com0 = [float(x) for x in p0]
    com1 = [float(x) for x in p1]
    collective_variable = cv

    # ----- BEGIN verbatim: BioSimSpace 2024.4.1 _funnel.py viewFunnel lines 1098-1149 -----
    vec_step = 2
    n_angle_samples = 8

    # Extract collective variable data.
    lower_wall = collective_variable.getLowerBound().getValue().angstroms().value()
    upper_wall = collective_variable.getUpperBound().getValue().angstroms().value()
    wall_width = collective_variable.getWidth().angstroms().value()
    beta_cent = collective_variable.getSteepness()
    s_cent = collective_variable.getInflection().angstroms().value()
    wall_buffer = collective_variable.getBuffer().angstroms().value()

    # ADAPTATION 3: BSS lines 1109-1110 (pseudo-atom `element` property) omitted.

    import numpy as _np

    # Calculate the vector defined by points p0 and p1.
    vec = _np.array(com1, dtype=float) - _np.array(com0, dtype=float)

    # BEWARE: inconsistency with linalg, if vec is a list and not an array!
    # Make it a unit vector.
    unit_vec = vec / _np.linalg.norm(vec)

    # Now to get orthogonal vectors:
    # https://math.stackexchange.com/questions/133177/finding-a-unit-vector-perpendicular-to-another-vector

    # Determine 1st orthogonal vector.
    if basis_ints is None:  # ADAPTATION 1
        a0 = _np.random.randint(1, 10)
        a1 = _np.random.randint(1, 10)
    else:  # ADAPTATION 1
        a0, a1 = basis_ints  # ADAPTATION 1
    a2 = -(a0 * vec[0] + a1 * vec[1]) / vec[2]
    a = _np.asarray([a0, a1, a2])
    unit_a = a / _np.linalg.norm(a)

    # Determine 2nd orthogonal vector.

    unit_b = _np.cross(unit_a, unit_vec)
    # Iterate along the selected vector
    funnel_coords = []
    for step in _np.arange(lower_wall, upper_wall + vec_step, vec_step):
        # iterate around a circle with its radius defined by the sigmoid function
        if radius_mode == "viewfunnel":  # ADAPTATION 2
            radius = (wall_width / (1 + _np.exp(beta_cent * (step - s_cent)))) + wall_buffer
        else:  # ADAPTATION 2
            radius = collective_variable.getExtent(Length(float(step), "angstrom")).angstroms().value()  # ADAPTATION 2
        for angle in _np.arange(-_np.pi, _np.pi, 2 * _np.pi / n_angle_samples):
            # Calculate parametric functions for this specific case
            # https://math.stackexchange.com/questions/73237/parametric-equation-of-a-circle-in-3d-space
            # Generate pseudoatoms along the axis.
            coord = (
                com0
                + unit_vec * step
                + radius * (_np.cos(angle) * unit_a + _np.sin(angle) * unit_b)
            )
            funnel_coords.append(coord)  # ADAPTATION 3
    # ----- END verbatim -----
    return np.array(funnel_coords)
