"""
Build a PLUMED input fragment defining GROUP and COORDINATION collective
variables from the G1/G2 result written by
`ligand_waterfp.g1_g2_selection.select_g1_g2`.

This produces a STARTING-POINT fragment, not a complete, ready-to-run
plumed.dat: it defines G1/G2 as atom GROUPs and a COORDINATION CV for each
against a water-oxygen group, using placeholder switching-function
parameters (R_0, NN, MM) that must be reviewed/tuned against your own
system's conventions (e.g. matching whatever P#/COORDINATION CVs are
already used elsewhere in your project's plumed.dat files) before use in
production. Nothing here is fit to, or copied from, any specific system's
real plumed.dat.

Usage:
    ligand-waterfp-build-cv --g1-g2 outputs/selection/g1_g2.yaml \\
        --water-group-def "GROUPA=<water oxygen atom indices>" \\
        --out outputs/ligand_cv/plumed_fragment.dat
"""
import argparse
from pathlib import Path
import yaml

from ligand_waterfp.g1_g2_selection.select_g1_g2 import SelectionResult

FRAGMENT_TEMPLATE = """\
# Ligand-side WaterFP CV fragment, generated by build_ligand_cv.py.
# G1 = anti-bulk pair (strongest hydration perturbation), G2 = bulk pair
# (most solvent-like). See `ligand_waterfp.g1_g2_selection.select_g1_g2` for how
# these atom serials were derived, and the `convergence` subpackage for
# the convergence check that validated the FP ranking behind them.
#
# STARTING POINT ONLY: review/tune R_0, NN, MM below (and the water
# reference group, if a full GROUPA=... atom list was not supplied) to
# match your own project's PLUMED conventions before running this in
# production.

G1: GROUP ATOMS={g1_serials}
G2: GROUP ATOMS={g2_serials}

{water_group_line}

g1_coord: COORDINATION GROUPA=G1 GROUPB={water_group_ref} R_0=0.32 NN=6 MM=12
g2_coord: COORDINATION GROUPA=G2 GROUPB={water_group_ref} R_0=0.32 NN=6 MM=12

PRINT ARG=g1_coord,g2_coord STRIDE=500 FILE=LIGAND_WATERFP_CV.dat
"""


def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--g1-g2", required=True, help="YAML written by `ligand_waterfp.g1_g2_selection.select_g1_g2`")
    p.add_argument("--water-group-def", default=None,
                    help="A full PLUMED GROUP line body for the water-oxygen reference group, e.g. "
                         "'GROUPA=1305-14858' (atom indices, force-field/system dependent). "
                         "If omitted, the fragment references a WATER_O group you must define yourself.")
    p.add_argument("--out", required=True)
    return p.parse_args()


def main():
    args = parse_args()

    # Validate the required input before processing, and echo the
    # resolved paths this run is using.
    g1_g2_path = Path(args.g1_g2)
    out_path = Path(args.out)

    if not g1_g2_path.is_file():
        raise SystemExit(f"[build_ligand_cv] --g1-g2 file not found: {g1_g2_path.resolve()}")

    print(f"[build_ligand_cv] g1_g2: {g1_g2_path.resolve()}")
    print(f"[build_ligand_cv] out: {out_path.resolve()}")

    with g1_g2_path.open() as f:
        data = yaml.safe_load(f)
    selection = SelectionResult.from_dict(data)

    g1_serials = ",".join(str(a.serial) for a in selection.G1)
    g2_serials = ",".join(str(a.serial) for a in selection.G2)

    if args.water_group_def:
        water_group_line = f"WATER_O: GROUP {args.water_group_def}"
        water_group_ref = "WATER_O"
    else:
        water_group_line = ("# TODO: define your own water-oxygen reference group, e.g.:\n"
                             "# WATER_O: GROUP ATOMS=<water oxygen atom indices>")
        water_group_ref = "WATER_O"

    fragment = FRAGMENT_TEMPLATE.format(
        g1_serials=g1_serials,
        g2_serials=g2_serials,
        water_group_line=water_group_line,
        water_group_ref=water_group_ref,
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write(fragment)

    print(f"[build_ligand_cv] G1 atoms (serials): {g1_serials}")
    print(f"[build_ligand_cv] G2 atoms (serials): {g2_serials}")
    print(f"[build_ligand_cv] wrote {out_path.resolve()}")


if __name__ == "__main__":
    main()
